# Generated by Django 4.0.3 on 2022-04-28 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
        ('pharmacie', '0001_initial'),
        ('med', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('le_type', models.CharField(choices=[('Traitement', 'Traitement'), ('Medicaments', 'Medicaments')], max_length=13)),
                ('description_de_traitement', models.CharField(max_length=255)),
                ('quantite', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('a_mutuelle', models.BooleanField(default=False)),
                ('nom_traitement', models.CharField(blank=True, max_length=255, null=True)),
                ('id_medicament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='med.meds')),
                ('id_pharmacie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacie.pharmacie')),
                ('id_visite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.visite')),
            ],
        ),
    ]
