# Generated by Django 4.0.3 on 2022-05-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0001_initial'),
        ('ordonnance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordonnance',
            name='id_medicament',
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='id_medicament',
            field=models.ManyToManyField(blank=True, to='med.meds'),
        ),
    ]
