# Generated by Django 4.0.3 on 2022-05-02 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0001_initial'),
        ('doctor', '0007_alter_appointement_status'),
        ('ordonnance', '0002_remove_ordonnance_id_medicament_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordonnance',
            name='date_purchase',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='ordonnance',
            name='id_medicament',
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='id_medicament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='med.meds'),
        ),
        migrations.AlterField(
            model_name='ordonnance',
            name='id_visite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordonnance', to='doctor.visite'),
        ),
    ]
