# Generated by Django 4.0.3 on 2022-05-02 20:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ordonnance', '0003_alter_ordonnance_date_purchase_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordonnance',
            options={'ordering': ['-date_created']},
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
