# Generated by Django 4.0.3 on 2022-05-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordonnance', '0004_alter_ordonnance_options_ordonnance_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordonnance',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
