# Generated by Django 4.0.3 on 2022-04-30 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('heure', models.CharField(choices=[('1', 'Matin'), ('2', 'Midi'), ('3', 'Apres')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('ville', models.CharField(max_length=250)),
                ('INP', models.IntegerField(primary_key=True, serialize=False)),
                ('speciality', models.CharField(max_length=255)),
                ('created', models.DateField(auto_now_add=True)),
                ('activated', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Visite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('medcin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visites', to='doctor.doctor')),
            ],
        ),
    ]
