# Generated by Django 4.0.3 on 2022-04-30 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
        ('doctor', '0001_initial'),
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visite',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visites', to='patient.patient'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='person_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='landing.person'),
        ),
        migrations.AddField(
            model_name='appointement',
            name='medcin_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointements', to='doctor.doctor'),
        ),
        migrations.AddField(
            model_name='appointement',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointements', to='patient.patient'),
        ),
    ]
