# Generated by Django 4.0.3 on 2022-05-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_appointement_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointement',
            name='status',
            field=models.IntegerField(choices=[('1', 'Accepted'), ('2', 'Waiting'), ('3', 'Refused')]),
        ),
    ]
