# Generated by Django 4.0.3 on 2022-05-03 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_alter_appointement_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointement',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='visite',
            options={'ordering': ['-date_created']},
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(max_length=255)),
                ('id_visite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visites', to='doctor.visite')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
