# Generated by Django 4.0.3 on 2022-05-03 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_alter_appointement_options_alter_visite_options_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='id_visite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.visite'),
        ),
    ]
