# Generated by Django 4.0.3 on 2022-05-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_alter_note_id_visite'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='adresse',
            field=models.CharField(default='Hay Salama', max_length=250),
            preserve_default=False,
        ),
    ]
