# Generated by Django 4.0.3 on 2022-05-01 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
        ('pharmacie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacie',
            name='user',
        ),
        migrations.AddField(
            model_name='pharmacie',
            name='person_id',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='landing.person'),
            preserve_default=False,
        ),
    ]
