# Generated by Django 4.0.3 on 2022-05-01 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0002_remove_pharmacie_user_pharmacie_person_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacie',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
