# Generated by Django 4.0.3 on 2022-04-30 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0002_initial'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllMutuelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('mutuelle_status', models.CharField(choices=[('P', 'Pending'), ('C', 'Complete')], default='P', max_length=1)),
                ('total', models.DecimalField(decimal_places=2, max_digits=7)),
                ('patient_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
                ('visite_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='doctor.visite')),
            ],
        ),
    ]
