# Generated by Django 4.0.3 on 2022-05-09 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0010_doctor_adresse'),
        ('mutuelle', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allmutuelle',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='allmutuelle',
            name='patient_id',
        ),
        migrations.AlterField(
            model_name='allmutuelle',
            name='visite_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.visite'),
        ),
    ]
