# Generated by Django 4.0.3 on 2022-04-28 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('landing', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.IntegerField(blank=True, null=True)),
                ('permission_privacy', models.BooleanField(default=False)),
                ('a_mutuelle', models.BooleanField(default=False)),
                ('immatriculation', models.IntegerField(null=True)),
                ('date_adhesion', models.DateField(null=True)),
                ('n_affiliation', models.IntegerField(null=True)),
                ('person_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='landing.person')),
            ],
        ),
    ]
