# Generated by Django 4.0.3 on 2022-05-09 14:58

from django.db import migrations
import thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='img',
            field=thumbnails.fields.ImageField(default='profile_pics/default.png', null=True, upload_to='profile_pics'),
        ),
    ]
