# Generated by Django 4.0.3 on 2022-05-09 15:20

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_alter_person_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='img',
            field=easy_thumbnails.fields.ThumbnailerImageField(default='profile_pics/default.png', null=True, upload_to='profile_pics'),
        ),
    ]
