# Generated by Django 4.0.3 on 2022-04-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meds',
            fields=[
                ('code', models.IntegerField(db_column='CODE', primary_key=True, serialize=False)),
                ('nom', models.TextField(blank=True, db_column='NOM', null=True)),
                ('dci1', models.TextField(blank=True, db_column='DCI1', null=True)),
                ('dosage1', models.TextField(blank=True, db_column='DOSAGE1', null=True)),
                ('unite_dosage1', models.TextField(blank=True, db_column='UNITE_DOSAGE1', null=True)),
                ('forme', models.TextField(blank=True, db_column='FORME', null=True)),
                ('presentation', models.TextField(blank=True, db_column='PRESENTATION', null=True)),
                ('ppv', models.FloatField(blank=True, db_column='PPV', null=True)),
                ('ph', models.FloatField(blank=True, db_column='PH', null=True)),
                ('prix_br', models.FloatField(blank=True, db_column='PRIX_BR', null=True)),
                ('princeps_generique', models.TextField(blank=True, db_column='PRINCEPS_GENERIQUE', null=True)),
                ('taux_remboursement', models.TextField(blank=True, db_column='TAUX_REMBOURSEMENT', null=True)),
            ],
        ),
    ]
